// <auto-generated />
using System;
using Control.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Control.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Control.Web.Data.Entities.Passanger", b =>
                {
                    b.Property<int>("PassangerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Adult");

                    b.Property<int>("Child");

                    b.Property<string>("Flight")
                        .IsRequired()
                        .HasMaxLength(4);

                    b.Property<int>("Infant");

                    b.Property<DateTime>("PublishOn");

                    b.Property<int>("Total");

                    b.HasKey("PassangerId");

                    b.ToTable("Passangers");
                });
#pragma warning restore 612, 618
        }
    }
}
