//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control.UIForms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Control.UIForms.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an address..
        /// </summary>
        public static string AddressEnter {
            get {
                return ResourceManager.GetString("AddressEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Flight Data.
        /// </summary>
        public static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an Adults Total..
        /// </summary>
        public static string AdultEnter {
            get {
                return ResourceManager.GetString("AdultEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults:.
        /// </summary>
        public static string Adults {
            get {
                return ResourceManager.GetString("Adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an Adults Total.
        /// </summary>
        public static string AdultsEntry {
            get {
                return ResourceManager.GetString("AdultsEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store on Device.
        /// </summary>
        public static string BtnDevice {
            get {
                return ResourceManager.GetString("BtnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Password.
        /// </summary>
        public static string BtnModifyPassword {
            get {
                return ResourceManager.GetString("BtnModifyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Password.
        /// </summary>
        public static string BtnRecoverPassword {
            get {
                return ResourceManager.GetString("BtnRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New User.
        /// </summary>
        public static string BtnRegisterNewUser {
            get {
                return ResourceManager.GetString("BtnRegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save On Server.
        /// </summary>
        public static string BtnSaveServer {
            get {
                return ResourceManager.GetString("BtnSaveServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Password.
        /// </summary>
        public static string BtnUpdatePassword {
            get {
                return ResourceManager.GetString("BtnUpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a Children Total..
        /// </summary>
        public static string ChildEnter {
            get {
                return ResourceManager.GetString("ChildEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children:.
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Children Total.
        /// </summary>
        public static string ChildrenEntry {
            get {
                return ResourceManager.GetString("ChildrenEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a city..
        /// </summary>
        public static string CityEnter {
            get {
                return ResourceManager.GetString("CityEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close session.
        /// </summary>
        public static string CloseSession {
            get {
                return ResourceManager.GetString("CloseSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a country..
        /// </summary>
        public static string CountryEnter {
            get {
                return ResourceManager.GetString("CountryEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the Report?.
        /// </summary>
        public static string DeleteReport {
            get {
                return ResourceManager.GetString("DeleteReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Flight.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an email..
        /// </summary>
        public static string EmailEnter {
            get {
                return ResourceManager.GetString("EmailEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an email..
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password incorrect..
        /// </summary>
        public static string EmailPasswordError {
            get {
                return ResourceManager.GetString("EmailPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid email..
        /// </summary>
        public static string EmailValidEnter {
            get {
                return ResourceManager.GetString("EmailValidEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the first name..
        /// </summary>
        public static string FirstNameEnter {
            get {
                return ResourceManager.GetString("FirstNameEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight:.
        /// </summary>
        public static string Flight {
            get {
                return ResourceManager.GetString("Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a Flight Number..
        /// </summary>
        public static string FlightEnter {
            get {
                return ResourceManager.GetString("FlightEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Flight Number.
        /// </summary>
        public static string FlightEntry {
            get {
                return ResourceManager.GetString("FlightEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot my password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an Image.
        /// </summary>
        public static string ImageEnter {
            get {
                return ResourceManager.GetString("ImageEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you take the picture?.
        /// </summary>
        public static string ImageTake {
            get {
                return ResourceManager.GetString("ImageTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the image to change it....
        /// </summary>
        public static string ImageTap {
            get {
                return ResourceManager.GetString("ImageTap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an Infants Total..
        /// </summary>
        public static string InfantEnter {
            get {
                return ResourceManager.GetString("InfantEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infants:.
        /// </summary>
        public static string Infants {
            get {
                return ResourceManager.GetString("Infants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an Infants Total.
        /// </summary>
        public static string InfantsEntry {
            get {
                return ResourceManager.GetString("InfantsEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the last name..
        /// </summary>
        public static string LastNameEnter {
            get {
                return ResourceManager.GetString("LastNameEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Store Device.
        /// </summary>
        public static string LocalPageTitle {
            get {
                return ResourceManager.GetString("LocalPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify User.
        /// </summary>
        public static string ModifyUserTitle {
            get {
                return ResourceManager.GetString("ModifyUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must have at least 6 characters length..
        /// </summary>
        public static string PasswordChart {
            get {
                return ResourceManager.GetString("PasswordChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the password confirm..
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the current password..
        /// </summary>
        public static string PasswordCurrent {
            get {
                return ResourceManager.GetString("PasswordCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password..
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect..
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirm does not match..
        /// </summary>
        public static string PasswordMatch {
            get {
                return ResourceManager.GetString("PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the new password..
        /// </summary>
        public static string PasswordNew {
            get {
                return ResourceManager.GetString("PasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Password.
        /// </summary>
        public static string PasswordPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Report.
        /// </summary>
        public static string PaxTitle {
            get {
                return ResourceManager.GetString("PaxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a phone number..
        /// </summary>
        public static string PhoneEnter {
            get {
                return ResourceManager.GetString("PhoneEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a Date..
        /// </summary>
        public static string PublisOnEnter {
            get {
                return ResourceManager.GetString("PublisOnEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string RegisterNewUser {
            get {
                return ResourceManager.GetString("RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New User.
        /// </summary>
        public static string RegisterUserTitle {
            get {
                return ResourceManager.GetString("RegisterUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark:.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Remarks.
        /// </summary>
        public static string RemarkEntry {
            get {
                return ResourceManager.GetString("RemarkEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me in this device.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover password.
        /// </summary>
        public static string RememberPasswordTitle {
            get {
                return ResourceManager.GetString("RememberPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report was NOT sent.
        /// </summary>
        public static string ReportNoSent {
            get {
                return ResourceManager.GetString("ReportNoSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string SetupTitle {
            get {
                return ResourceManager.GetString("SetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a Total Passengers..
        /// </summary>
        public static string TotalEnter {
            get {
                return ResourceManager.GetString("TotalEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Total Passengers.
        /// </summary>
        public static string TotalEntry {
            get {
                return ResourceManager.GetString("TotalEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Passengers:.
        /// </summary>
        public static string TotalPassangers {
            get {
                return ResourceManager.GetString("TotalPassangers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Email.
        /// </summary>
        public static string UserPlaceHolder {
            get {
                return ResourceManager.GetString("UserPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated!.
        /// </summary>
        public static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome:.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
